### ISSUE TITLE
format suggestion

### ISSUE THREAD

**Issue by stineot** [ivamalovic/historical_recipes#5]
Finally! Someones doing a project on scrambling eggs! I think it would be even greater if the format could be changed from txt to md, maybe? 
What do you think?

Regards,
Stine

**Comment by ivamalovic** [comment]
@stineot @tilmannvs 

Hei,
Great idea, Stine!
As they say, great minds think alike.
Lærke has already suggested it, and I asked her to do it.
I am sorry I did not run this by you two first. Hope you will forgive...

Best,
Ivana

**Comment by stineot** [comment]
No worries!
I'll check out Lærkes changes.

Stine
